### ISSUE TITLE
Failed to load the language from the levels-language-ruby package

### ISSUE THREAD

**Issue by mitall** [lakrme/atom-levels-language-ruby#1]
Failed to load the language from the levels-language-ruby package
TypeError: this.textEditor.setGrammar is not a function

Das ist einem Studenten passiert und mir jetzt auch, nachdem ich das ruby-Paket geupdated hab. Das erscheint manchmal beim Start von Atom, manchmal aber auch nicht. Ich glaub es passiert immer abwechselnd einmal nicht und dann doch wieder. Wenn es auftritt, dann erscheint das Terminal nicht. 

Minimale Reproduktion:
Atom starten
Neuen Tab Öffnen
Ruby (Levels) als Grammatik einstellen
Atom schließen
Atom öffnen

**Comment by ichistmeinname** [comment]
Am Freitag hat sich das für mich so rausgehört, als wenn es ein Windows-spezifischer Fehler wäre -- ich habe aber auch gerade die Fehlermeldung auf meinem Mac OS System bekommen.

**Comment by lakrme** [comment]
Ich kann den Fehler auch reproduzieren. Er trat bei mir aber erst nach dem Update auf Atom 1.2 auf und scheint mir ein Atom-Bug zu sein.

Der Fehler tritt bei der Paket-spezifischen Deserialisierung auf: Mit Levels verknüpfte Tabs werden vom Paket serialisiert und nach dem Neustart von Atom wiederhergestellt, sobald das zugehörige Sprachpaket geladen wurde. Diese Deserialisierung wird über eine API-Funktionen von Atom unterstützt, welche nun scheinbar fehlerhaft arbeitet. Aus diesem Grund tritt der Fehler auch nur jedes "zweite Mal" auf. Immer dann wenn der Fehler nicht auftritt konnte das Sprachpaket ja vorher nicht geladen werden, weshalb beim Schließen von Atom auch keine Tabs serialisiert wurden, d.h. beim erneuten Starten findet die Deserialisierung nicht statt.

Es gibt auch aktuelle Issues bzgl. der Paket-spezifischen Deserialisierung, z.B. [hier](https://github.com/atom/atom/issues/9600).

Ich guck's mir nochmal genauer an wenn ich Zeit habe. Falls es wirklich ein Atom-Bug ist hilft wohl nur abwarten.

**Comment by lakrme** [comment]
Offenbar hat sich mit Version 1.1 oder 1.2 was an der oben erwähnten API-Funktion geändert, weshalb ich den Fehler nun doch per Hand beseitigen musste. Ist mit [diesem Commit](https://github.com/lakrme/atom-levels/commit/02ea1d2177534187baabba81df1dcec53ce13ce1) (hoffentlich) geschehen und wurde auch schon als Patch veröffentlicht.
