### ISSUE TITLE
Feature request for embedded shell

### ISSUE THREAD

**Issue by ichistmeinname** [lakrme/atom-levels-language-ruby#2]
The current shell-plugin (I assume you didn't implement tit by yourself?) does not support:
- colors (as used by sqlite_console and sqlite_connector)
- a fixed width (currently, the window width becomes scrollable -- but does not scroll automatically!)
- the keyboard layout of the system its running on
- to set the cursor to an arbitrary position (this does not seem that important, but it is deeply connected with the ability to copy the output text)

**Comment by lakrme** [comment]
Verschoben nach [hier](https://github.com/lakrme/atom-levels/issues/12)
